apiVersion: "apps/v1"
kind: Deployment
metadata:
  namespace: uc4-support
  name: imaginary
spec:
  replicas: 3

  selector:
    matchLabels:
      app: imaginary

  template:
    metadata:
      namespace: uc4-support
      labels:
        app: imaginary
    spec:
      containers:
        - name: imaginary
          image: h2non/imaginary:latest
          imagePullPolicy: Always
          env:
            - name: PORT
              value: "9000"
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
          ports:
            - name: management
              containerPort: 9000
---
apiVersion: v1
kind: Service
metadata:
  namespace: uc4-support
  name: imaginary
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: imaginary
  type: LoadBalancer