apiVersion: "apps/v1"
kind: Deployment
metadata:
  namespace: uc4-lagom
  name: group
spec:
  replicas: 2

  selector:
    matchLabels:
      app: group

  template:
    metadata:
      namespace: uc4-lagom
      labels:
        app: group
    spec:
      containers:
        - name: group
          image: "uc4official/group_service:$GROUP_VERSION"
          imagePullPolicy: Always
          
          env:
            - name: JAVA_OPTS
              value: "-Xms2G -Xmx2G -Dconfig.resource=prod-application.conf"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: secret
            - name: UC4_MASTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: uc4-master-secret
                  key: secret
            - name: UC4_KAFKA_SALT
              valueFrom:
                secretKeyRef:
                  name: uc4-kafka-salt
                  key: secret
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.strimzi-kafka-brokers.kafka"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: HYPERLEDGER_USERNAME
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-org1
                  key: username
            - name: HYPERLEDGER_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-org1
                  key: password
            - name: HYPERLEDGER_ORGANISATION_ID
              value: org1MSP
            - name: HYPERLEDGER_ORGANISATION_NAME
              value: org1
            - name: HYPERLEDGER_CHANNEL
              value: mychannel
            - name: HYPERLEDGER_CHAINCODE
              value: uc4-cc
            - name: HYPERLEDGER_CA_URL
              value: "https://rca-org1.hlf:7052"
            - name: HYPERLEDGER_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-admin-org1
                  key: username
            - name: HYPERLEDGER_REGISTRATION_SYSTEM
              valueFrom:
                secretKeyRef:
                  name: credentials.scala-registration-admin-org1
                  key: username
              
          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
              
          ports:
            - name: management
              containerPort: 8558
              
          volumeMounts:
            - name: cert
              mountPath: /var/secrets
            - name: certorg1
              mountPath: /var/secrets/org
            - name: connection
              mountPath: /var/libs/configmaps
              readOnly: true
              
          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
            
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
            
      volumes:
        - name: cert
          secret:
            secretName: cert.tls-ca
        - name: certorg1
          secret:
            secretName: cert.rca-org1
        - name: connection
          configMap:
            name: connection-profile
---
apiVersion: v1
kind: Service
metadata:
  namespace: uc4-lagom
  name: group
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: group
  type: LoadBalancer
