apiVersion: "apps/v1"
kind: Deployment
metadata:
  namespace: uc4-lagom
  name: report
spec:
  replicas: 2

  selector:
    matchLabels:
      app: report

  template:
    metadata:
      namespace: uc4-lagom
      labels:
        app: report
    spec:
      containers:
        - name: report
          image: "uc4official/report_service:$REPORT_VERSION"
          imagePullPolicy: Always
          env:
            - name: JAVA_OPTS
              value: "-Xms2G -Xmx2G -Dconfig.resource=prod-application.conf -Dlagom.akka.discovery.service-name-mappings.pdfprocessing.lookup=_http._tcp.pdfprocessing.uc4-support"
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: application-secret
                  key: secret
            - name: POSTGRESQL_URL
              value: "jdbc:postgresql://postgres.postgres/uc4report"
            - name: POSTGRESQL_USERNAME
              valueFrom:
                secretKeyRef:
                  name: postgres-report
                  key: username
            - name: POSTGRESQL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-report
                  key: password
            - name: UC4_MASTER_SECRET
              valueFrom:
                secretKeyRef:
                  name: uc4-master-secret
                  key: secret
            - name: UC4_KAFKA_SALT
              valueFrom:
                secretKeyRef:
                  name: uc4-kafka-salt
                  key: secret
            - name: KAFKA_SERVICE_NAME
              value: "_tcp-clients._tcp.strimzi-kafka-brokers.kafka"
            - name: REQUIRED_CONTACT_POINT_NR
              value: "2"
            - name: KEYSTORE_PATH
              value: "/opt/docker/share/pdf/keystore.jks"

          resources:
            limits:
              memory: 512Mi
            requests:
              cpu: 0.25
              memory: 512M
          ports:
            - name: management
              containerPort: 8558

          volumeMounts:
            - name: signaturefiles
              mountPath: /opt/docker/share/pdf

          readinessProbe:
            httpGet:
              path: "/ready"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20
          livenessProbe:
            httpGet:
              path: "/alive"
              port: management
            periodSeconds: 10
            failureThreshold: 10
            initialDelaySeconds: 20

      volumes:
        - name: signaturefiles
          configMap:
            name: files
---
apiVersion: v1
kind: Service
metadata:
  namespace: uc4-lagom
  name: report
spec:
  ports:
    - name: http
      port: 80
      targetPort: 9000
  selector:
    app: report
  type: LoadBalancer