apiVersion: v1
kind: ConfigMap
metadata:
  namespace: postgres
  name: postgres-config
  labels:
    app: postgres
data:
  POSTGRES_USER: postgresadmin
  POSTGRES_PASSWORD: admin1234
  SERVICES: authentication course certificate user